name: deploy on heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: senha@01
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "senha@01"
          envkey_POSTGRES_DB: "students_test"
          envkey_DATABASE_URL: "postgres://postgres:senha@01@localhost:5432/students_test"
          file_name: .env.test
